FROM golang:latest

ENV GOPATH=/go
ENV GOARCH=arm
ENV GOARM=6
# ENV CC=arm-linux-gnueabi-gcc

ENV BEATS=filebeat
ENV BEATS_VERSION=7.15.1

COPY ./build.sh /build.sh
RUN [ "mkdir", "-p", "/go" ]
RUN [ "mkdir", "/build" ]

CMD "/build.sh"
